#!/bin/bash
if [ -z $1 ]; then
  echo "usage: `basename $0` user@server.tld:path/to/project.git"
elif [ ! -d ".git" ]; then
  echo "Please run `basename $0` from the root of a git repository"
else
  git remote add origin $1
  git config branch.master.remote origin
  git config branch.master.merge refs/heads/master
  git push --all
  git pull
fi

